allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  electron-winstaller: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - esbuild
  - sharp
  - unrs-resolver
