import type { ListeningSet } from "./types";

/** 5 段原创 IELTS 风格听力（对话/独白，各 6 题）。非版权材料。*/
export const LISTENING_SETS: ListeningSet[] = [
  {
    id: "ls-course",
    title: "Language Course Enquiry",
    lines: [
      { speaker: "W", text: "Hello, I'm calling about the evening language courses. Could you give me some details?" },
      { speaker: "M", text: "Of course. We currently offer five languages: French, Spanish, German, Japanese and Mandarin. Each course runs for twelve weeks." },
      { speaker: "W", text: "And when do the classes take place?" },
      { speaker: "M", text: "Classes meet twice a week, on Tuesdays and Thursdays, from seven until nine in the evening." },
      { speaker: "W", text: "How much does it cost?" },
      { speaker: "M", text: "The standard fee is three hundred and fifty pounds. If you enrol before the fifteenth of September, there is a twenty per cent early discount." },
      { speaker: "W", text: "Do I need to buy anything else?" },
      { speaker: "M", text: "Textbooks are required and cost about forty pounds. The online audio materials, however, are free." },
      { speaker: "W", text: "And how big are the classes?" },
      { speaker: "M", text: "We keep them small, usually between eight and twelve students, so everyone gets plenty of practice." },
    ],
    questions: [
      { id: "q1", type: "gapfill", prompt: "How many languages does the school offer? ______", answer: "5" },
      { id: "q2", type: "gapfill", prompt: "Each course runs for ______ weeks.", answer: "12" },
      { id: "q3", type: "mcq", prompt: "Which days do classes meet?",
        options: ["Monday and Wednesday", "Tuesday and Thursday", "Wednesday and Friday", "Every weekday"],
        answer: "Tuesday and Thursday" },
      { id: "q4", type: "gapfill", prompt: "The early enrolment discount is ______ per cent.", answer: "20" },
      { id: "q5", type: "gapfill", prompt: "Textbooks cost about ______ pounds.", answer: "40" },
      { id: "q6", type: "gapfill", prompt: "Class size is between ______ and twelve students.", answer: "8" },
    ],
  },
  {
    id: "ls-library",
    title: "Library Membership",
    lines: [
      { speaker: "M", text: "Good morning. I'd like to join the city library. What do I need to do?" },
      { speaker: "W", text: "Welcome. I'll just need some proof of address and a form of identification, such as a passport or driving licence." },
      { speaker: "M", text: "I have a recent electricity bill and my passport. Is that enough?" },
      { speaker: "W", text: "That's perfect. Standard membership is free, and it lets you borrow up to eight items at a time." },
      { speaker: "M", text: "How long can I keep them?" },
      { speaker: "W", text: "Books can be borrowed for three weeks. DVDs and magazines are one week only. You can renew online unless someone else has reserved the item." },
      { speaker: "M", text: "What happens if I return something late?" },
      { speaker: "W", text: "There's a fine of twenty pence per day for each item. The maximum fine on any single item is five pounds." },
      { speaker: "M", text: "And are there computers I can use?" },
      { speaker: "W", text: "Yes, there are twenty public computers on the first floor. Members get two hours of free internet access each day." },
    ],
    questions: [
      { id: "q1", type: "mcq", prompt: "What does the man use as proof of identity?",
        options: ["A student card", "A passport", "A birth certificate", "A bank card"],
        answer: "A passport" },
      { id: "q2", type: "gapfill", prompt: "Standard membership lets you borrow up to ______ items.", answer: "8" },
      { id: "q3", type: "gapfill", prompt: "Books can be borrowed for ______ weeks.", answer: "3" },
      { id: "q4", type: "gapfill", prompt: "The late fine is ______ pence per day per item.", answer: "20" },
      { id: "q5", type: "gapfill", prompt: "The maximum fine on a single item is ______ pounds.", answer: "5" },
      { id: "q6", type: "gapfill", prompt: "There are ______ public computers on the first floor.", answer: "20" },
    ],
  },
  {
    id: "ls-lecture",
    title: "A Lecture on Honeybees",
    lines: [
      { speaker: "N", text: "Good afternoon, everyone. Today's talk is about honeybees and the remarkable way they communicate." },
      { speaker: "N", text: "A single hive may contain up to sixty thousand bees, yet almost all of them are female workers. There is usually just one queen." },
      { speaker: "N", text: "When a worker finds a good source of food, she returns to the hive and performs what scientists call a waggle dance." },
      { speaker: "N", text: "The direction of the dance indicates the direction of the food relative to the sun, while the duration of the waggle shows how far away it is." },
      { speaker: "N", text: "Bees are vital pollinators. It is estimated that about one third of the food we eat depends, directly or indirectly, on their work." },
      { speaker: "N", text: "In recent decades, however, bee populations have declined sharply. The main causes are thought to be pesticides, disease, and the loss of wild-flower habitats." },
    ],
    questions: [
      { id: "q1", type: "gapfill", prompt: "A hive may contain up to ______ thousand bees.", answer: "60" },
      { id: "q2", type: "mcq", prompt: "Most bees in a hive are:",
        options: ["Male drones", "Female workers", "Young queens", "Guard bees"],
        answer: "Female workers" },
      { id: "q3", type: "gapfill", prompt: "The dance that indicates food location is called the ______ dance.", answer: "waggle" },
      { id: "q4", type: "mcq", prompt: "What does the duration of the waggle show?",
        options: ["The type of flower", "How far away the food is", "The time of day", "The number of bees"],
        answer: "How far away the food is" },
      { id: "q5", type: "gapfill", prompt: "About one ______ of our food depends on bees.", answer: "third" },
      { id: "q6", type: "mcq", prompt: "Which is NOT given as a cause of bee decline?",
        options: ["Pesticides", "Disease", "Loss of wild-flower habitats", "Rising sea levels"],
        answer: "Rising sea levels" },
    ],
  },
  {
    id: "ls-trip",
    title: "Planning a Field Trip",
    lines: [
      { speaker: "W", text: "Hi Tom, I'm organising the geography field trip. Can we go over the arrangements?" },
      { speaker: "M", text: "Sure, Anna. Where are we taking the students this year?" },
      { speaker: "W", text: "We're going to the Riverdale Nature Reserve. The coach leaves school at eight fifteen sharp, so students should arrive by eight." },
      { speaker: "M", text: "How long is the journey?" },
      { speaker: "W", text: "About ninety minutes. We should be there by quarter to ten, which gives us the whole morning at the site." },
      { speaker: "M", text: "What should the students bring?" },
      { speaker: "W", text: "Sturdy walking shoes, a waterproof jacket, and a packed lunch. They don't need money, as the reserve entry is covered by the school." },
      { speaker: "M", text: "And what will they actually be doing there?" },
      { speaker: "W", text: "In the morning they'll collect water samples from the river. After lunch, a ranger will give a guided walk through the woodland." },
      { speaker: "M", text: "Sounds well organised. When do we get back?" },
      { speaker: "W", text: "The coach leaves the reserve at three, so we'll be back at school around four thirty." },
    ],
    questions: [
      { id: "q1", type: "gapfill", prompt: "The coach leaves school at ______.", answer: "8:15" },
      { id: "q2", type: "gapfill", prompt: "The journey takes about ______ minutes.", answer: "90" },
      { id: "q3", type: "mcq", prompt: "What are students told to bring?",
        options: ["Money for entry", "A packed lunch and waterproof jacket", "A laptop", "Swimming clothes"],
        answer: "A packed lunch and waterproof jacket" },
      { id: "q4", type: "mcq", prompt: "What will students do in the morning?",
        options: ["Collect water samples", "Take a guided walk", "Visit a museum", "Draw maps"],
        answer: "Collect water samples" },
      { id: "q5", type: "mcq", prompt: "Who leads the afternoon activity?",
        options: ["A teacher", "A ranger", "A student", "A scientist"],
        answer: "A ranger" },
      { id: "q6", type: "gapfill", prompt: "They will arrive back at school around ______.", answer: "4:30" },
    ],
  },
  {
    id: "ls-gym",
    title: "Joining a Fitness Centre",
    lines: [
      { speaker: "M", text: "Hello, I'm interested in joining the fitness centre. What memberships do you have?" },
      { speaker: "W", text: "We have three options. The basic plan gives you gym access only. The standard plan adds all group classes, and the premium plan also includes the swimming pool and sauna." },
      { speaker: "M", text: "How much is the standard plan?" },
      { speaker: "W", text: "It's forty-five pounds a month. There's also a one-off joining fee of twenty pounds for all new members." },
      { speaker: "M", text: "What are your opening hours?" },
      { speaker: "W", text: "We open at six in the morning and close at ten at night on weekdays. At weekends we close earlier, at eight in the evening." },
      { speaker: "M", text: "Do you offer any introductory sessions?" },
      { speaker: "W", text: "Yes, every new member gets one free session with a personal trainer, who'll help you set up a programme." },
      { speaker: "M", text: "Great. Is there parking?" },
      { speaker: "W", text: "There's a car park behind the building. It's free for members for the first two hours." },
    ],
    questions: [
      { id: "q1", type: "mcq", prompt: "Which plan includes the swimming pool?",
        options: ["Basic", "Standard", "Premium", "None of them"],
        answer: "Premium" },
      { id: "q2", type: "gapfill", prompt: "The standard plan costs ______ pounds a month.", answer: "45" },
      { id: "q3", type: "gapfill", prompt: "The one-off joining fee is ______ pounds.", answer: "20" },
      { id: "q4", type: "gapfill", prompt: "On weekdays the centre closes at ______ at night.", answer: "10" },
      { id: "q5", type: "mcq", prompt: "What does every new member receive?",
        options: ["A free towel", "One free session with a personal trainer", "A month free", "A locker key"],
        answer: "One free session with a personal trainer" },
      { id: "q6", type: "gapfill", prompt: "Parking is free for members for the first ______ hours.", answer: "2" },
    ],
  },
];

